# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Farms2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Farms2
  use_modular_headers!
  # Pods for Farms
  pod 'RealmSwift', '=10.0.0-alpha.4'
end
